version: "3.2"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=core_service
    ports:
      - "5432:5432"

  joinMe:
    image: joinme
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"